# Changes here will be overwritten by Copier
_commit: d2d63a1
_src_path: python-package-template-copier
author_email: daemo00@gmail.com
author_full_name: Simone Rubino
cli: true
dependency: pydantic
optional_dependency: ''
package_name: TryPydantic
