name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Allow to install global packages
      run: pip install pipx
    - name: Install test dependencies
      run: pipx install tox
    - name: Test
      run: tox -e py,report
    - name: Codecov
      uses: codecov/codecov-action@v3
